dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
dotenv: .env
networks:
  #     verify: False
  # goerli:
  sepolia:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}

